package Model;

public enum ActionEnum {
    MOVE_X_POSITIVE,
    MOVE_X_NEGATIVE,
    MOVE_Z_POSITIVE,
    MOVE_Z_NEGATIVE,
    MOVE_Y_SPEEDUP,
    ROTATION_X_POSITIVE,
    ROTATION_X_NEGATIVE,
    ROTATION_Y_POSITIVE,
    ROTATION_Y_NEGATIVE,
    ROTATION_Z_POSITIVE,
    ROTATION_Z_NEGATIVE,
    NONE
}
